---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alterconso
  namespace: alterconso
spec:
  values:
    webapp:
      env_as_values:
        MYSQL_ROOT_PASSWORD: |-
          AgCOfgSiEcSXoGmTZldMyYvocBhGraKABc0mjd3wWzbvsB6uI3UwgNyFbRZ49QNsfMSdfPEYz2V9gHGt/ANcuynIUFeodVSen9JkdemInkNOJnYD7L8LIuV04lgfnITcGQCTwYgyWJzgqVBjqsoLReG8U1bIDqRXENsZ6tUgCuP6s1TOFISlHRDahxcyZnbjlonE6NSHMtdpgaDfl
          naw54o6ll8sIOgYvK8nXeNUkTfhvYgeAnhX4Fofl3MvPn/XMSsIQdJbN9Y7PF9O38L7JWT916SlaK8lQAJth+6cZQO1S34U48kSb1dUXCslfpT9tRIPbTpyT02OI1z8n9+SLSRIH74aoXfaqggsTHJZfSR/Ey2OFVAyr5om3/00LmFeT5Q2wAwhcC4oXYGwziT95oCrM8dhPZmxIH
          EacdNL8bkVMMewFjxdiUF+0iuFpRNAnuXLe4Vh0R7CHiHRBPqPX6BAHEjET+pTvnwbbLytYw9tE5myPndOvZ/W6JI1Qx5xkl145Ds41imIUbJtjv6+Mo6uc1ZCLkteUPoo3sLZB9yjasxtQAoYvqHIyw8fGPxDsQfjhxHeYyB2qTOilweik4UdSVrTz1roaSmG5ffDU+2fuJRqB9I
          hBwu0vFshb8hGemHNh+BhV8RzMFIz6xLzGviqhkVL1rvElUmsdLrnLLVcUOf0r494zgSlv4Tm4L/UVQoPoqQucA==
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: "mkcert-issuer"
        hosts:
          - name: alterconso.gpenaud.localhost
            path: /
            tls: true
      vhost: alterconso.gpenaud.localhost
    database:
      env:
        MYSQL_PASSWORD: alterconso
      env_as_secrets:
        MYSQL_ROOT_PASSWORD: |-
          AgCOfgSiEcSXoGmTZldMyYvocBhGraKABc0mjd3wWzbvsB6uI3UwgNyFbRZ49QNsfMSdfPEYz2V9gHGt/ANcuynIUFeodVSen9JkdemInkNOJnYD7L8LIuV04lgfnITcGQCTwYgyWJzgqVBjqsoLReG8U1bIDqRXENsZ6tUgCuP6s1TOFISlHRDahxcyZnbjlonE6NSHMtdpgaDfl
          naw54o6ll8sIOgYvK8nXeNUkTfhvYgeAnhX4Fofl3MvPn/XMSsIQdJbN9Y7PF9O38L7JWT916SlaK8lQAJth+6cZQO1S34U48kSb1dUXCslfpT9tRIPbTpyT02OI1z8n9+SLSRIH74aoXfaqggsTHJZfSR/Ey2OFVAyr5om3/00LmFeT5Q2wAwhcC4oXYGwziT95oCrM8dhPZmxIH
          EacdNL8bkVMMewFjxdiUF+0iuFpRNAnuXLe4Vh0R7CHiHRBPqPX6BAHEjET+pTvnwbbLytYw9tE5myPndOvZ/W6JI1Qx5xkl145Ds41imIUbJtjv6+Mo6uc1ZCLkteUPoo3sLZB9yjasxtQAoYvqHIyw8fGPxDsQfjhxHeYyB2qTOilweik4UdSVrTz1roaSmG5ffDU+2fuJRqB9I
          hBwu0vFshb8hGemHNh+BhV8RzMFIz6xLzGviqhkVL1rvElUmsdLrnLLVcUOf0r494zgSlv4Tm4L/UVQoPoqQucA==
      local:
        path: /mnt/k3s/alterconso
      nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - t490s

