---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alterconso
resources:
  - namespace.yaml
  - dockerconfig-secret.yaml
  - helm/repository.yaml
  - helm/release.yaml
  - image/repository.yaml
  - image/policy.yaml
  - image/updateautomation.yaml